version: '3.8'

services:
  mysql:
      image: mysql:8.0.29
      container_name: db_ajudaai
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ajudaai
      env_file: .env
      cap_add:
        - SYS_NICE
      ports:
        - 3306:3306
      volumes:
        - mysql:/var/lib/mysql
      expose:
        - '3306'
      networks:
        - nt_ajudaai

volumes:
  mysql:

networks:
  nt_ajudaai:
    driver: bridge

